apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtasker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudtasker
  template:
    metadata:
      labels:
        app: cloudtasker
    spec:
      containers:
      - name: cloudtasker
        image: ://amazonaws.com
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
